name: Auto Publish Website
on:
  push:
    branches:
    - main
permissions:
  contents: write
jobs:
  call-workflow-passing-data:
    uses: dappsteros-io/github/.github/workflows/push_test_server.yml@main
    with:
      project-name: dappsteros-local-storage
    secrets:
      ZEROTIER_NETWORK_ID: ${{ secrets.ZEROTIER_NETWORK_ID }}
      ZEROTIER_CENTRAL_TOKEN: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      SSH_ROBOT_URL: ${{ secrets.SSH_ROBOT_URL }}
